Repository moby/datakit, pull requests merged in 2018-03, with the labels that each got.

#619 Fix ci/skeleton example
  ci/skeleton/.dockerignore
  ci/skeleton/Dockerfile
Labels: area/build, area/ci, kind/bug

#624 ci: add support for Docker parameter 'network'
  ci/src/cI_docker.ml
  ci/src/cI_docker.mli
  ci/src/datakit_ci.mli
Labels: area/ci, kind/enhancement

#627 Add trouble-shooting section to the README
  ci/README.md
Labels: area/ci, kind/docs, kind/enhancement
